a=read.csv("~/Downloads/matrix3.csv", header = F)
head(a)
row.names(a)<-1:300
headmap(a)
heatmap(a)
a = data.matrix(a)
heatmap(a)
par(cex=0.5)
d <- distfunc(a)
fit <- hclustfunc(d)
par(cex=0.5)
plot(fit)
heatmap(a)
par(cex=0.5)
heatmap(a)
heatmap(a, cexRow = 0.5, cexCol = 0.5)
heatmap(a, cexRow = 0.25, cexCol = 0.5)
?heatmap
par(cex=0.5)
plot(fit)
